export const DEFAULT_PAGE_SIZE = 50;
export const MAX_PAGE_SIZE = 100;
export const DEFAULT_SCAN_EVIDENCE_LIMIT = 50;
export const DEFAULT_ANALYSIS_EVIDENCE_LIMIT = 20;
export const DEFAULT_WORKER_CONCURRENCY = 2;
export const DEFAULT_SCAN_SOURCE_LIMIT = 16;
export const MAX_INSTANCE_SOURCES = 64;
export const MAX_WORKER_CONCURRENCY = 8;
export const MAX_EVENTS_PER_SCAN = 8;
export const MAX_OBSERVATIONS_PER_EVENT = 20;
export const MAX_PORTFOLIOS = 8;
export const MAX_PORTFOLIO_WALLETS = 16;
export const MAX_PORTFOLIO_HOLDINGS = 50;
export const DEFAULT_REGISTRY_TOP_N = 1_000;
export const MAX_REGISTRY_TOP_N = 2_000;
export const MAX_REGISTRY_ASSETS = 4_000;
export const MAX_ALIASES_PER_ASSET = 32;
export const MAX_CAIP19_PER_ASSET = 16;
export const MAX_ASSETS_PER_DOCUMENT = 12;
export const MAX_RELEVANCE_TERMS = 96;
export const MAX_ENGLISH_STOPWORDS = 2048;
export const MAX_CLUSTER_TOKENS = 64;
export const MAX_ASSET_SEARCH_RESULTS = 20;
export const MAX_REGISTRY_LIST_BYTES = 8_000_000;
export const MAX_REGISTRY_MARKETS_PAGES = 8;
export const COINGECKO_MARKETS_PER_PAGE = 250;
export const DEFAULT_REGISTRY_SEED_INTERVAL_HOURS = 24;
export const MAX_REGISTRY_SEED_INTERVAL_HOURS = 168;
export const DEFAULT_OBSERVE_CONCURRENCY = 2;
export const MAX_OBSERVE_CONCURRENCY = 4;
export const DEFAULT_OBSERVE_BATCH_SIZE = 100;
export const MAX_OBSERVE_BATCH_SIZE = 100;
export const DEFAULT_OBSERVE_MAX_SUBJECTS = 1_000;
export const MAX_OBSERVE_SUBJECTS = 4_000;
export const DEFAULT_OBSERVE_RETENTION_DAYS = 90;
export const MIN_OBSERVE_RETENTION_DAYS = 14;
export const MAX_OBSERVE_RETENTION_DAYS = 365;
export const DEFAULT_OBSERVE_PRICE_INTERVAL_SECONDS = 60;
export const MIN_OBSERVE_PRICE_INTERVAL_SECONDS = 60;
export const MAX_OBSERVE_PRICE_INTERVAL_SECONDS = 300;
export const MAX_OBSERVE_PINS = 100;
export const MAX_SERIES_WINDOW = 512;
export const MAX_CHART_SPARK_POINTS = 96;
export const MAX_CHART_MARKERS = 32;
export const MAX_MORNING_WATCHLISTS = 32;
export const MAX_MORNING_ASSETS = 50;
export const MAX_MORNING_EVENTS_PER_ASSET = 8;
export const MAX_MORNING_SIGNALS_PER_ASSET = 8;
export const MAX_MORNING_CATALYSTS_PER_ASSET = 8;
export const MAX_ASSET_EVIDENCE = 50;
export const MAX_ASSET_CLAIMS = 50;
export const MAX_ASSET_IDENTITIES = 32;
export const MORNING_LOOKBACK_MS = 24 * 60 * 60 * 1000;
export const MAX_MORNING_SINCE_MS = 7 * 24 * 60 * 60 * 1000;
export const UPCOMING_CATALYST_HORIZON_MS = 14 * 24 * 60 * 60 * 1000;
export const CHANGE_24H_TOLERANCE_MS = 2 * 60 * 60 * 1000;
export const DEFAULT_CHART_LOOKBACK_MS = 7 * 24 * 60 * 60 * 1000;
export const DEFAULT_DETECTOR_WINDOW = 20;
export const DEFAULT_DETECTOR_ABS_Z = 3;
export const MAX_RETENTION_DELETE_BATCH = 5_000;
export const MAX_RETENTION_LOOPS = 40;
export const OBSERVE_CLOCK_SKEW_MS = 5 * 60 * 1000;
export const MAX_OBSERVE_BODY_BYTES = 1_000_000;
export const MAX_CATALYST_KINDS = 32;
export const MAX_FEED_BODY_BYTES = 2_000_000;
export const MAX_FEED_ITEMS = 50;
export const MAX_FEED_ITEM_CHARS = 4_000;
export const MIN_NATIVE_COMPLETE_CHARS = 400;
export const MAX_ROBOTS_TXT_CHARS = 20_000;
export const MAX_HOST_ROBOTS_CACHE = 1_024;
export const ROBOTS_CACHE_TTL_MS = 24 * 60 * 60 * 1000;
export const MAX_FEED_REDIRECTS = 3;
export const DEFAULT_FEED_POLL_INTERVAL_SECONDS = 300;
export const MIN_FEED_POLL_INTERVAL_SECONDS = 60;
export const MAX_FEED_POLL_INTERVAL_SECONDS = 3_600;
export const MAX_FEED_BACKOFF_SECONDS = 3_600;
export const MAX_SEARXNG_ASSET_QUERIES = 12;
export const MAX_SEARXNG_QUERY_CHARS = 512;
export const MAX_SEARXNG_BODY_BYTES = 1_000_000;
export const MAX_SEARXNG_ENGINES = 16;
export const MAX_UNRESPONSIVE_ENGINES = 16;
export const MAX_DEFILLAMA_BODY_BYTES = 5_000_000;
export const MAX_DEFILLAMA_PROTOCOL_FETCHES = 16;
export const MAX_DEFILLAMA_CHAIN_SLUGS = 8;
export const MAX_DEFILLAMA_HACKS_PER_POLL = 50;
export const MAX_DEFILLAMA_COIN_IDS = 100;
export const MAX_DEFILLAMA_CALLS_PER_MINUTE = 60;
export const DEFAULT_DEFILLAMA_INTERVAL_MS = 15 * 60 * 1000;
export const DEFILLAMA_HACKS_INTERVAL_MS = 60 * 60 * 1000;
export const DEFILLAMA_PROTOCOLS_INTERVAL_MS = 24 * 60 * 60 * 1000;
export const DEFAULT_TVL_DRAWDOWN_PCT = 15;
export const DEFAULT_TVL_DRAWDOWN_FLOOR_USD = 1_000_000;
export const DEFAULT_PEG_DEVIATION_PCT = 1;
export const TVL_DRAWDOWN_LOOKBACK_MS = 24 * 60 * 60 * 1000;
export const HOURS_PER_YEAR = 24 * 365;
export const HYPERLIQUID_FUNDING_PERIOD_HOURS = 1;
export const BINANCE_FUNDING_PERIOD_HOURS = 8;
export const DEFAULT_FUTURES_INTERVAL_MS = 60_000;
export const MIN_FUTURES_INTERVAL_MS = 30_000;
export const MAX_FUTURES_INTERVAL_MS = 15 * 60 * 1000;
export const BINANCE_OI_INTERVAL_MS = 5 * 60 * 1000;
export const MAX_HYPERLIQUID_BODY_BYTES = 2_000_000;
export const MAX_BINANCE_BODY_BYTES = 2_000_000;
export const MAX_HYPERLIQUID_UNIVERSE = 512;
export const MAX_BINANCE_PREMIUM_ROWS = 512;
export const MAX_BINANCE_OI_SYMBOLS = 40;
export const MAX_BINANCE_WS_BUFFER = 256;
export const MAX_BINANCE_WS_FRAME_AGE_MS = 120_000;
export const BINANCE_WS_RECONNECT_MIN_MS = 1_000;
export const BINANCE_WS_RECONNECT_MAX_MS = 30_000;
export const BINANCE_USED_WEIGHT_SOFT_LIMIT = 2_000;
export const MAX_OBSERVATIONS_PER_POLL = 12_000;
export const DEFAULT_OI_CHANGE_PCT = 20;
export const DEFAULT_FUNDING_DIVERGENCE_APR_PCT = 10;
export const DEFAULT_LIQUIDATION_BURST_USD = 10_000_000;
export const MARKET_STRESS_FUNDING_WINDOW = 168;
export const MARKET_STRESS_FUNDING_MIN_SAMPLES = 20;
export const MARKET_STRESS_FUNDING_MAX_GAP_MS = 2 * 60 * 60 * 1000;
export const OI_CHANGE_LOOKBACK_MS = 60 * 60 * 1000;
export const OI_CHANGE_MAX_GAP_MS = 15 * 60 * 1000;
export const FUNDING_DIVERGENCE_MAX_GAP_MS = 20 * 60 * 1000;
export const FUTURES_NATIVE_SUBJECT_RE = /^(hyperliquid|binance-futures):[A-Za-z0-9._-]+$/;
export const OBSERVE_NATIVE_SUBJECT_RE =
  /^(hyperliquid|binance-futures|polymarket|kalshi):[A-Za-z0-9._-]+$/;
export const DEFAULT_PREDICTION_INTERVAL_MS = 15 * 60 * 1000;
export const MAX_PREDICTION_BODY_BYTES = 2_000_000;
export const MAX_PREDICTION_MARKETS = 50;
export const MAX_POLYMARKET_CALLS_PER_MINUTE = 60;
export const MAX_KALSHI_CALLS_PER_MINUTE = 30;
export const MAX_KALSHI_MARKET_PAGES = 5;
export const MAX_SNAPSHOT_BODY_BYTES = 2_000_000;
export const MAX_SNAPSHOT_SPACES = 16;
export const MAX_SNAPSHOT_PROPOSALS = 50;
export const MAX_SNAPSHOT_CALLS_PER_MINUTE = 60;
export const MAX_EDGAR_BODY_BYTES = 2_000_000;
export const MAX_EDGAR_FILINGS = 50;
export const MAX_EDGAR_DOCUMENT_CHARS = 8_000;
export const MAX_EDGAR_DOCUMENT_FETCHES = 8;
export const MAX_EDGAR_REQUESTS_PER_SECOND = 10;
export const MIN_EDGAR_CALL_GAP_MS = 100;
export const DEFAULT_EDGAR_BUSINESS_POLL_SECONDS = 120;
export const DEFAULT_EDGAR_OFFHOURS_POLL_SECONDS = 900;
export const MAX_EFTS_HITS = 100;
export const MAX_EFTS_KEYWORDS = 8;
export const EFTS_KEYWORD_INTERVAL_MS = 60 * 60 * 1000;
export const MAX_EQUITIES_REGISTRY = 2_000;
export const MAX_OPENFIGI_JOBS_UNAUTH = 10;
export const MAX_OPENFIGI_JOBS_AUTH = 100;
export const OPENFIGI_UNAUTH_PER_MINUTE = 25;
export const OPENFIGI_AUTH_PER_MINUTE = 250;
export const MAX_OPENFIGI_BODY_BYTES = 1_000_000;
export const DEFAULT_SNAPSHOT_LOOKBACK_SECONDS = 7 * 24 * 60 * 60;
export const MAX_INBOUND_WEBHOOK_BODY_BYTES = 1_000_000;
export const MAX_WEBHOOK_ADDRESSES = 256;
export const MAX_LABELED_ADDRESSES = 256;
export const MAX_ADDRESS_ACTIVITY_ITEMS = 64;
export const INBOUND_WEBHOOK_MAX_AGE_MS = 10 * 60 * 1000;
export const MAX_X_AUTHORS = 30;
export const MAX_X_KEYWORDS = 16;
export const MAX_X_LOOKBACK_HOURS = 168;
export const MAX_X_RESULTS = 100;
export const MAX_X_PAGES = 3;
export const MAX_X_QUERY_CHARS = 512;
export const MAX_X_BODY_BYTES = 2_000_000;
export const DEFAULT_X_MONTHLY_READ_BUDGET = 5_000;
export const MIN_X_MONTHLY_READ_BUDGET = 10;
export const MAX_X_MONTHLY_READ_BUDGET = 40_000;
export const MAX_DISCORD_CHANNELS = 8;
export const MAX_DISCORD_KEYWORDS = 16;
export const MAX_DISCORD_MESSAGES_PER_CHANNEL = 100;
export const MAX_DISCORD_LOOKBACK_HOURS = 72;
export const MAX_DISCORD_PAGES_PER_CHANNEL = 5;
export const MAX_DISCORD_THREAD_PAGES = 2;
export const MAX_DISCORD_THREADS_PER_CHANNEL = 16;
export const MAX_DISCORD_BODY_BYTES = 2_000_000;
export const MAX_DISCORD_ATTACHMENTS = 8;
export const MAX_DISCORD_REACTIONS = 16;
export const MAX_IDENTITY_TRACK_ROWS = 2_000;
export const MAX_EVENT_IDENTITY_CANDIDATES = 32;
export const MAX_LIFECYCLE_TRANSITIONS_PER_EVENT = 32;
export const MAX_SCORECARD_ROWS = 2_000;
export const MAX_OUTCOME_EVENTS_PER_TICK = 100;
export const MAX_OUTCOME_SERIES_POINTS = 512;
export const OUTCOME_POINT_TOLERANCE_MS = 15 * 60 * 1000;
export const EVENT_JOIN_CLOCK_SKEW_MS = 5 * 60 * 1000;
export const DEFAULT_LARGE_TRANSFER_USD = 1_000_000;
export const DEFAULT_TRANSFER_MIN_USD = 1_000;
export const DEFAULT_EXPLOIT_TRANSFER_USD = 10_000_000;
export const MAX_PRICES_HISTORY_POINTS = 512;
export const DEFAULT_ODDS_JUMP_1H_PP = 15;
export const DEFAULT_ODDS_JUMP_24H_PP = 25;
export const DEFAULT_ODDS_LIQUIDITY_USD = 10_000;
export const ODDS_JUMP_1H_MS = 60 * 60 * 1000;
export const ODDS_JUMP_24H_MS = 24 * 60 * 60 * 1000;
export const ODDS_JUMP_1H_MAX_GAP_MS = 20 * 60 * 1000;
export const ODDS_JUMP_24H_MAX_GAP_MS = 2 * 60 * 60 * 1000;
export const ODDS_JUMP_VENUE_MAX_GAP_MS = 40 * 60 * 1000;
export const MAX_NOTIFICATION_TARGETS = 16;
export const MAX_NOTIFICATION_ROUTES_PER_AGENT = 16;
export const MAX_OBSERVATION_ALERT_RULES = 32;
export const MIN_OBSERVATION_ALERT_WINDOW_MINUTES = 1;
export const MAX_OBSERVATION_ALERT_WINDOW_MINUTES = 10_080;
export const DEFAULT_PCT_DROP_WINDOW_MINUTES = 1_440;
export const DEFAULT_PCT_MOVE_WINDOW_MINUTES = 5;
export const MAX_DISCORD_WEBHOOK_PER_MINUTE = 30;
export const MAX_DISCORD_CONTENT_CHARS = 2_000;
export const MAX_DISCORD_EMBED_DESCRIPTION_CHARS = 1_000;
export const MAX_DISCORD_EMBED_TOTAL_CHARS = 6_000;
export const MAX_DISCORD_RETRY_AFTER_SEC = 5;
export const MAX_DISCORD_EXECUTE_RETRIES = 2;
export const DISCORD_WEBHOOK_QUEUE_CAP = 32;

export function clampPageSize(value: unknown, fallback = DEFAULT_PAGE_SIZE): number {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    return fallback;
  }
  return Math.min(MAX_PAGE_SIZE, Math.max(1, Math.floor(parsed)));
}

export function clampPositiveInt(
  value: unknown,
  fallback: number,
  max: number = Number.MAX_SAFE_INTEGER,
): number {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    return fallback;
  }
  return Math.min(max, Math.max(1, Math.floor(parsed)));
}

export function takeBounded<T>(items: readonly T[], limit: number): T[] {
  return items.slice(0, Math.max(0, limit));
}

export function parsePageCursor(before?: string): Date | undefined {
  if (!before) {
    return undefined;
  }
  const value = new Date(before);
  return Number.isNaN(value.getTime()) ? undefined : value;
}
