import { describe, expect, it } from "vitest";
import {
  BINANCE_FUNDING_PERIOD_HOURS,
  clampPageSize,
  clampPositiveInt,
  DEFAULT_DEFILLAMA_INTERVAL_MS,
  DEFAULT_DETECTOR_ABS_Z,
  DEFAULT_DETECTOR_WINDOW,
  DEFAULT_EXPLOIT_TRANSFER_USD,
  DEFAULT_FEED_POLL_INTERVAL_SECONDS,
  DEFAULT_FUNDING_DIVERGENCE_APR_PCT,
  DEFAULT_FUTURES_INTERVAL_MS,
  DEFAULT_LARGE_TRANSFER_USD,
  DEFAULT_LIQUIDATION_BURST_USD,
  DEFAULT_OBSERVE_PRICE_INTERVAL_SECONDS,
  DEFAULT_ODDS_JUMP_1H_PP,
  DEFAULT_ODDS_JUMP_24H_PP,
  DEFAULT_ODDS_LIQUIDITY_USD,
  DEFAULT_OI_CHANGE_PCT,
  DEFAULT_PAGE_SIZE,
  DEFAULT_PEG_DEVIATION_PCT,
  DEFAULT_PREDICTION_INTERVAL_MS,
  DEFAULT_REGISTRY_TOP_N,
  DEFAULT_SNAPSHOT_LOOKBACK_SECONDS,
  DEFAULT_TRANSFER_MIN_USD,
  DEFAULT_TVL_DRAWDOWN_FLOOR_USD,
  DEFAULT_TVL_DRAWDOWN_PCT,
  DEFAULT_X_MONTHLY_READ_BUDGET,
  HOURS_PER_YEAR,
  HYPERLIQUID_FUNDING_PERIOD_HOURS,
  INBOUND_WEBHOOK_MAX_AGE_MS,
  MAX_ADDRESS_ACTIVITY_ITEMS,
  MAX_ASSETS_PER_DOCUMENT,
  MAX_BINANCE_OI_SYMBOLS,
  MAX_BINANCE_WS_BUFFER,
  MAX_CATALYST_KINDS,
  MAX_DEFILLAMA_BODY_BYTES,
  MAX_DEFILLAMA_CHAIN_SLUGS,
  MAX_DEFILLAMA_HACKS_PER_POLL,
  MAX_DEFILLAMA_PROTOCOL_FETCHES,
  MAX_DISCORD_LOOKBACK_HOURS,
  MAX_DISCORD_PAGES_PER_CHANNEL,
  MAX_DISCORD_THREAD_PAGES,
  MAX_EVENT_IDENTITY_CANDIDATES,
  MAX_FEED_BODY_BYTES,
  MAX_FEED_ITEMS,
  MAX_FEED_POLL_INTERVAL_SECONDS,
  MAX_HYPERLIQUID_UNIVERSE,
  MAX_INBOUND_WEBHOOK_BODY_BYTES,
  MAX_KALSHI_CALLS_PER_MINUTE,
  MAX_KALSHI_MARKET_PAGES,
  MAX_LABELED_ADDRESSES,
  MAX_LIFECYCLE_TRANSITIONS_PER_EVENT,
  MAX_OBSERVATIONS_PER_POLL,
  MAX_OBSERVE_SUBJECTS,
  MAX_OUTCOME_EVENTS_PER_TICK,
  MAX_PAGE_SIZE,
  MAX_POLYMARKET_CALLS_PER_MINUTE,
  MAX_PREDICTION_MARKETS,
  MAX_REGISTRY_TOP_N,
  MAX_SCORECARD_ROWS,
  MAX_SEARXNG_ASSET_QUERIES,
  MAX_SEARXNG_BODY_BYTES,
  MAX_SEARXNG_ENGINES,
  MAX_SNAPSHOT_BODY_BYTES,
  MAX_SNAPSHOT_CALLS_PER_MINUTE,
  MAX_SNAPSHOT_PROPOSALS,
  MAX_SNAPSHOT_SPACES,
  MAX_WEBHOOK_ADDRESSES,
  MAX_X_AUTHORS,
  MAX_X_MONTHLY_READ_BUDGET,
  MAX_X_PAGES,
  MAX_X_RESULTS,
  MIN_FEED_POLL_INTERVAL_SECONDS,
  MIN_X_MONTHLY_READ_BUDGET,
  parsePageCursor,
  takeBounded,
} from "./limits.js";

describe("bounded resource limits", () => {
  it("clamps page size to the documented 1–100 range", () => {
    expect(clampPageSize(undefined)).toBe(DEFAULT_PAGE_SIZE);
    expect(clampPageSize("12")).toBe(12);
    expect(clampPageSize(0)).toBe(1);
    expect(clampPageSize(10_000)).toBe(MAX_PAGE_SIZE);
  });

  it("does not keep more items than the explicit bound", () => {
    const items = Array.from({ length: 10_000 }, (_, index) => index);
    expect(takeBounded(items, 25)).toHaveLength(25);
    expect(takeBounded(items, 25).at(-1)).toBe(24);
  });

  it("caps worker concurrency at the configured maximum", () => {
    expect(clampPositiveInt(99, 2, 8)).toBe(8);
    expect(clampPositiveInt("3", 2, 8)).toBe(3);
  });

  it("parses a page cursor or rejects invalid dates", () => {
    expect(parsePageCursor("2026-09-11T07:00:00.000Z")?.toISOString()).toBe(
      "2026-09-11T07:00:00.000Z",
    );
    expect(parsePageCursor("not-a-date")).toBeUndefined();
    expect(parsePageCursor()).toBeUndefined();
  });

  it("keeps the CoinGecko registry seed at the documented top-N bound", () => {
    expect(DEFAULT_REGISTRY_TOP_N).toBe(1_000);
    expect(MAX_REGISTRY_TOP_N).toBe(2_000);
    expect(MAX_ASSETS_PER_DOCUMENT).toBe(12);
    expect(clampPositiveInt(5_000, DEFAULT_REGISTRY_TOP_N, MAX_REGISTRY_TOP_N)).toBe(2_000);
    expect(DEFAULT_OBSERVE_PRICE_INTERVAL_SECONDS).toBe(60);
    expect(MAX_OBSERVE_SUBJECTS).toBe(4_000);
    expect(DEFAULT_DETECTOR_WINDOW).toBe(20);
    expect(DEFAULT_DETECTOR_ABS_Z).toBe(3);
    expect(MAX_CATALYST_KINDS).toBe(32);
    expect(DEFAULT_FEED_POLL_INTERVAL_SECONDS).toBe(300);
    expect(MIN_FEED_POLL_INTERVAL_SECONDS).toBe(60);
    expect(MAX_FEED_POLL_INTERVAL_SECONDS).toBe(3_600);
    expect(MAX_FEED_BODY_BYTES).toBe(2_000_000);
    expect(MAX_FEED_ITEMS).toBe(50);
    expect(MAX_SEARXNG_ASSET_QUERIES).toBe(12);
    expect(MAX_SEARXNG_BODY_BYTES).toBe(1_000_000);
    expect(MAX_SEARXNG_ENGINES).toBe(16);
    expect(MAX_DEFILLAMA_BODY_BYTES).toBe(5_000_000);
    expect(MAX_DEFILLAMA_PROTOCOL_FETCHES).toBe(16);
    expect(MAX_DEFILLAMA_CHAIN_SLUGS).toBe(8);
    expect(MAX_DEFILLAMA_HACKS_PER_POLL).toBe(50);
    expect(DEFAULT_DEFILLAMA_INTERVAL_MS).toBe(15 * 60 * 1000);
    expect(DEFAULT_TVL_DRAWDOWN_PCT).toBe(15);
    expect(DEFAULT_TVL_DRAWDOWN_FLOOR_USD).toBe(1_000_000);
    expect(DEFAULT_PEG_DEVIATION_PCT).toBe(1);
    expect(DEFAULT_FUTURES_INTERVAL_MS).toBe(60_000);
    expect(DEFAULT_OI_CHANGE_PCT).toBe(20);
    expect(DEFAULT_FUNDING_DIVERGENCE_APR_PCT).toBe(10);
    expect(DEFAULT_LIQUIDATION_BURST_USD).toBe(10_000_000);
    expect(HOURS_PER_YEAR).toBe(8760);
    expect(HYPERLIQUID_FUNDING_PERIOD_HOURS).toBe(1);
    expect(BINANCE_FUNDING_PERIOD_HOURS).toBe(8);
    expect(MAX_HYPERLIQUID_UNIVERSE).toBe(512);
    expect(MAX_BINANCE_OI_SYMBOLS).toBe(40);
    expect(MAX_BINANCE_WS_BUFFER).toBe(256);
    expect(MAX_OBSERVATIONS_PER_POLL).toBe(12_000);
    expect(DEFAULT_ODDS_JUMP_1H_PP).toBe(15);
    expect(DEFAULT_ODDS_JUMP_24H_PP).toBe(25);
    expect(DEFAULT_ODDS_LIQUIDITY_USD).toBe(10_000);
    expect(DEFAULT_PREDICTION_INTERVAL_MS).toBe(15 * 60 * 1000);
    expect(MAX_PREDICTION_MARKETS).toBe(50);
    expect(MAX_POLYMARKET_CALLS_PER_MINUTE).toBe(60);
    expect(MAX_KALSHI_CALLS_PER_MINUTE).toBe(30);
    expect(MAX_KALSHI_MARKET_PAGES).toBe(5);
    expect(MAX_SNAPSHOT_SPACES).toBe(16);
    expect(MAX_SNAPSHOT_PROPOSALS).toBe(50);
    expect(MAX_SNAPSHOT_CALLS_PER_MINUTE).toBe(60);
    expect(MAX_SNAPSHOT_BODY_BYTES).toBe(2_000_000);
    expect(DEFAULT_SNAPSHOT_LOOKBACK_SECONDS).toBe(7 * 24 * 60 * 60);
    expect(MAX_INBOUND_WEBHOOK_BODY_BYTES).toBe(1_000_000);
    expect(MAX_WEBHOOK_ADDRESSES).toBe(256);
    expect(MAX_LABELED_ADDRESSES).toBe(256);
    expect(MAX_ADDRESS_ACTIVITY_ITEMS).toBe(64);
    expect(INBOUND_WEBHOOK_MAX_AGE_MS).toBe(10 * 60 * 1000);
    expect(DEFAULT_LARGE_TRANSFER_USD).toBe(1_000_000);
    expect(DEFAULT_TRANSFER_MIN_USD).toBe(1_000);
    expect(DEFAULT_EXPLOIT_TRANSFER_USD).toBe(10_000_000);
    expect(MAX_X_AUTHORS).toBe(30);
    expect(MAX_X_RESULTS).toBe(100);
    expect(MAX_X_PAGES).toBe(3);
    expect(DEFAULT_X_MONTHLY_READ_BUDGET).toBe(5_000);
    expect(MIN_X_MONTHLY_READ_BUDGET).toBe(10);
    expect(MAX_X_MONTHLY_READ_BUDGET).toBe(40_000);
    expect(MAX_DISCORD_LOOKBACK_HOURS).toBe(72);
    expect(MAX_DISCORD_PAGES_PER_CHANNEL).toBe(5);
    expect(MAX_DISCORD_THREAD_PAGES).toBe(2);
    expect(MAX_EVENT_IDENTITY_CANDIDATES).toBe(32);
    expect(MAX_LIFECYCLE_TRANSITIONS_PER_EVENT).toBe(32);
    expect(MAX_SCORECARD_ROWS).toBe(2_000);
    expect(MAX_OUTCOME_EVENTS_PER_TICK).toBe(100);
  });
});
