import { MAX_RELEVANCE_TERMS, takeBounded } from "@riddlr/domain";

export const CRYPTO_RELEVANCE_TERMS = [
  "crypto",
  "cryptocurrency",
  "cryptocurrencies",
  "bitcoin",
  "ethereum",
  "stablecoin",
  "stablecoins",
  "blockchain",
  "defi",
  "token",
  "tokens",
  "memecoin",
  "altcoin",
  "web3",
  "on-chain",
  "onchain",
  "nft",
  "dao",
  "airdrop",
  "depeg",
  "depegged",
  "perpetual",
  "perpetuals",
  "perp",
  "perps",
  "mempool",
  "validator",
  "validators",
  "staking",
  "hack",
  "exploit",
  "unlock",
  "digital asset",
  "digital assets",
  "binance",
  "coinbase",
  "kraken",
  "okx",
  "bybit",
  "bitfinex",
  "gemini",
  "uniswap",
  "aave",
  "hyperliquid",
  "dydx",
  "gmx",
  "polymarket",
  "kalshi",
  "coindesk",
  "cointelegraph",
  "tether",
  "circle",
  "solana",
  "avalanche",
  "polygon",
  "arbitrum",
  "optimism",
  "cardano",
  "litecoin",
  "dogecoin",
  "chainlink",
  "metamask",
  "opensea",
] as const;

export function cryptoRelevanceTerms(): string[] {
  return takeBounded([...CRYPTO_RELEVANCE_TERMS], MAX_RELEVANCE_TERMS);
}
